config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get "/home" => "welcome#index"
  root "welcome#index"

  get '/search' => 'search#search'
  
  resources :sessions, only: [:new, :create, :destroy] do
    delete :destroy, on: :collection
  end

  resources :users do
    get :before_approval, on: :collection
  end
  resources :contacts, only: [:new, :create, :show]
  resources :categories

  resources :profiles do
    resources :projects
    resources :skills
    resources :educations
    resources :experiences
    resources :contacts, only: [:new, :create, :show]
  end

  resources :password_resets

  resources :contacts, only: [:new, :create]

  get "users/:id/edit_password" => "users#edit_password", as: :edit_password
  patch "users/:id/update_password" => "users#update_password"

  get "messages/data" => "messages#data"
  resources :messages

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  attr_accessor :current_password

  has_one :profile, dependent: :destroy

  validates :password, length: {minimum:6}, on: :create
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true,
                    uniqueness: true,
                    format: /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  validates :password, presence: true, if: :changing_password?
  validates :password_confirmation, presence: true, if: :changing_password?

  # Include model in search
  include PgSearch
  multisearchable against: [:first_name, :last_name]
  
  def full_name
    "#{first_name} #{last_name}".titleize
  end

  def send_password_reset
    generate_token(:password_reset_token)
    self.password_reset_sent_at = Time.zone.now
    save!
    UserMailer.password_reset(self).deliver_now
  end

  def generate_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64
    end while User.exists?(column => self[column])
  end


  # after_create :send_admin_mail
  #  def send_admin_mail
  #    AdminMailer.new_user_waiting_for_approval(self).deliver
  #  end


  private

 def changing_password?
   current_password.present?
 end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :only_admin, only: [:index]

  def index
     @pending_users = User.where(approved: false, admin: false)
     @approved_users = User.where(approved: true, admin: false)
     render :index
  end

  def before_approval
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      sign_in(@user)
      redirect_to before_approval_users_path
    else
      render :new
    end
  end

  def show
    @user = User.find params[:id]
  end

  def edit
    @user = User.find params[:id]
  end

  def update
    @user = User.find params[:id]
    if @user.update user_params
      if current_user.admin
        UsersApprovalMailer.send_approval(@user).deliver_now
        redirect_to users_path, notice: "User approved"
      else
        if current_user.profile == nil
          redirect_to new_profile_path, notice: "User updated successfully."
        else
          redirect_to profile_path(current_user_profile), notice: "User updated successfully."
        end
      end
    else
      flash[:notice] = "User not updated."
      render :edit
    end
  end


  def destroy
    @user = User.find params[:id]
    dependent_profile = Profile.find_by_user_id(@user)
    dependent_profile.destroy if dependent_profile
    @user.destroy
    redirect_to users_path, notice: "User deleted successfully!"
  end

  def edit_password
    @user = User.find params[:id]
  end

  def update_password
  @user = User.find params[:id]
  if @user.authenticate(user_params[:current_password]) && @user.update(edit_password_params)
    redirect_to root_path, notice: "You have changed your password"
  else
    flash.now[:alert] = "make sure password is correct"
    render :edit_password
  end
end

  private

  def user_params
    params.require(:user).permit(:email, :first_name, :last_name, :password, :password_confirmation, :approved, :admin, :current_password)
  end

  def edit_password_params
    params.require(:user).permit([:current_password, :password, :password_confirmation])
  end


end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_edit_form.html.erb
<%= simple_form_for @user, :url => {:action => "update_password"} do |f| %>
  <%= f.input :current_password %>
  <%= f.input :password  %>
  <%= f.input :password_confirmation  %>
  <%= f.button :submit, class: "btn btn-primary"  %>
  <% end %>

app/views/users/_form.html.erb
<%= simple_form_for @user do |f| %>
  <%= f.input :first_name %>
  <%= f.input :last_name %>
  <%= f.input :email  %>
  <% if !user_signed_in? %>
  <%= f.input :password  %>
  <%= f.input :password_confirmation  %>
  <% end %>
  <%= f.button :submit, class: "btn btn-primary"  %>
  <%= link_to "Change Password", edit_password_path(current_user) if user_signed_in? %>
<% end %>

app/views/users/before_approval.html.erb
<div class="before-approval">
	<div class="container">
		<div class="codecore-logo-container">
			<%= image_tag('codecore-alumni.png') %>
		</div>
		<p>You have signed up successfully, but your account has not been approved by your administrator yet.</p>
		<%= link_to "Back to Homepage", root_path, class: "btn btn-default" %>
	</div>
</div>

app/views/users/create_failure.js.erb
alert("User cannot be created! Please check errors.")

app/views/users/create_pending.js.erb
$.get(root_path).fadeIn(1000);

app/views/users/edit.html.erb
<div class="container">
	<div class="edit-user">
		<div class="col-xs 12">
		  <h1>Edit User</h1>
		  <%= render "form" %>
		</div>
	</div>
</div>

app/views/users/edit_password.html.erb
<div class="container">
	<div class="edit-password">
		<div class="col-xs 12">
  		<h1>Edit Password</h1>
  		<%= render 'edit_form' %>
		</div>
	</div>
</div>

app/views/users/index.html.erb
<div class="container">
  <h1 style="text-align: center">Welcome to the Admin Control Panel!</h1>

  <div id="pending_users" class="col-sm-6">
    <h2>Pending Users</h2>
    <div class="container">
      <% @pending_users.each do |user| %>
        <div id="<%= dom_id(user) %>" class="row">
          <div class="col-sm-6">
            <p><%= user.full_name %><br><%= user.email %></p>
          </div>
          <div class="col-sm-6 text-right">
            <%= link_to "Approve", user_path(id: user, user: {approved: true}), method: :patch, class: "btn btn-success"  %>
            <%= link_to "Delete", user_path(user), method: :delete, data: {confirm: "Are you sure you want to delete #{user.full_name}?"}, class: "btn btn-primary" %>
          </div>
        </div>
        <hr>
      <% end %>
    </div>
  </div>

  <div id="approved_users" class="col-sm-6">
    <h2>Approved Users</h2>
    <div class="container">
      <% @approved_users.each do |user| %>
        <div id="<%= dom_id(user) %>" class="row">
          <div class="col-sm-6">
            <p><%= user.full_name %><br><%= user.email %></p>
          </div>
          <div class="col-sm-6 text-right">
            <%= link_to "Delete", user_path(user), method: :delete, data: {confirm: "Are you sure you want to delete #{user.full_name}?"}, class: "btn btn-primary" %>
          </div>
        </div>
        <hr>
      <% end %>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="container">
	<div class="create-user">
		<div class="col-xs 12">
    <h1>Create User</h1>
    <%= render "form" %>
		</div>
	</div>
</div>

app/views/users/update_failed.js.erb
alert("User update failed!");

app/views/users/update_user.js.erb
$("#<%= dom_id(@user) %>").fadeOut(400, function(){
  $("#approved_users").append($(this));
  // $(this).remove();
});