config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get "/home" => "welcome#index"
  root "welcome#index"

  get '/search' => 'search#search'
  
  resources :sessions, only: [:new, :create, :destroy] do
    delete :destroy, on: :collection
  end

  resources :users do
    get :before_approval, on: :collection
  end
  resources :contacts, only: [:new, :create, :show]
  resources :categories

  resources :profiles do
    resources :projects
    resources :skills
    resources :educations
    resources :experiences
    resources :contacts, only: [:new, :create, :show]
  end

  resources :password_resets

  resources :contacts, only: [:new, :create]

  get "users/:id/edit_password" => "users#edit_password", as: :edit_password
  patch "users/:id/update_password" => "users#update_password"

  get "messages/data" => "messages#data"
  resources :messages

end

app/models/project.rb
class Project < ActiveRecord::Base
  before_validation :smart_add_project_url_protocol, :smart_add_github_url_protocol
  belongs_to :profile

  # MODEL VALIDATIONS
  validates :title, presence: true, uniqueness: true
  validates :description, presence: true, uniqueness:true

  #simple validation to ensure that the URL is valid
  validates :project_url, :url => {:allow_blank => true}
  validates :github_url, :url => {:allow_blank => true}

  # Include model in search
  include PgSearch
  multisearchable against: [:description, :title]
  
  protected
 #needed to make sure it checks for http first
  def smart_add_project_url_protocol
    unless self.project_url.empty?
      unless self.project_url.include?("http")
        unless self.project_url[/\^http:\/\//] || self.project_url[/\^https:\/\//]
          self.project_url = "http://#{self.project_url}"
        end
      end
    end
  end

  def smart_add_github_url_protocol
    unless self.github_url.empty?
      unless self.github_url.include?("http")
        unless self.github_url[/\^http:\/\//] || self.github_url[/\^https:\/\//]
          self.github_url = "http://#{self.github_url}"
        end
      end
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  before_action :find_project, only: [:edit, :update, :destroy]
  before_action :find_profile, only: [:edit, :update, :destroy]
  before_action :authenticate_user
  before_action :authorize_user, only: [:edit, :update, :destroy]


  def create
    @project = Project.new project_params
    @project.profile = current_user_profile
    if @project.save
      redirect_to edit_profile_path(current_user_profile, anchor: 'projects'), notice: "Project added."
      else
      render :new
    end
  end

  def edit
  end

  def update
    if @project.update project_params
      redirect_to profile_path(@profile), notice: "Project updated"
    else
      render :edit
    end
  end

  def destroy
    @project.destroy
    redirect_to profile_path(@profile, anchor: 'projects'), notice: "Project removed"
  end

  private

  def find_project
    @project = Project.find params[:id]
  end

  def project_params
    params.require(:project).permit(:title, :description, :project_url, :github_url)
  end

  def user_from_request
    Profile.find_by_id(params[:profile_id]).user
  end

  def authorize_user
    if !(can? :manage, @project) || !((user_from_request == current_user) || (current_user.admin))
      redirect_to root_path, alert: "ACCESS DENIED"
    end
  end

end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_display_projects.html.erb
<div class="col-sm-12">
  <% @profile.projects.order(created_at: :desc).each do |project| %>
    <div class="row">
      <div class="col-sm-9">
        <h3><%= project.title %></h3>
        <p><%= project.description %></p>
        <% if can? :manage, @profile %>
          <%= link_to "Edit", edit_profile_project_path(@profile, project), class: "btn btn-primary" %>
          <%= link_to "Delete", profile_project_path(@profile, project), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-primary" %>
        <% end %>
      </div>
      <div class="col-sm-3 text-right">
        <div class="btn-profile-container">
          <%= link_to "View Project", project.project_url, target: "_blank", class: "btn btn-default" %><br>
          <%= link_to "View GitHub", project.github_url, target: "_blank", class: "btn btn-default" %>
        </div><!-- .btn-profile-container -->
      </div>
    </div>
    <hr>
  <% end %>
</div>

app/views/projects/_form.html.erb
  <ul>
    <% @project.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>

<%= simple_form_for [@profile, @project] do |f| %>
  <%= f.input :title %>
  <%= f.input :description %>
  <%= f.input :project_url %>
  <%= f.input :github_url, label: fa_icon("github"), label_html: {class: "form-link-icon"} %>
  <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/projects/edit.html.erb
<div class="col-sm-4 col-sm-offset-4">
<h1>Edit Project</h1>

<%= render "form" %>
</div>

app/views/projects/new.html.erb
<div class="col-sm-4 col-sm-offset-4">
<h1>Projects</h1>

<%= render "form" %>
</div>