config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get "/home" => "welcome#index"
  root "welcome#index"

  get '/search' => 'search#search'
  
  resources :sessions, only: [:new, :create, :destroy] do
    delete :destroy, on: :collection
  end

  resources :users do
    get :before_approval, on: :collection
  end
  resources :contacts, only: [:new, :create, :show]
  resources :categories

  resources :profiles do
    resources :projects
    resources :skills
    resources :educations
    resources :experiences
    resources :contacts, only: [:new, :create, :show]
  end

  resources :password_resets

  resources :contacts, only: [:new, :create]

  get "users/:id/edit_password" => "users#edit_password", as: :edit_password
  patch "users/:id/update_password" => "users#update_password"

  get "messages/data" => "messages#data"
  resources :messages

end

app/models/experience.rb
class Experience < ActiveRecord::Base
  before_validation :smart_add_url_protocol
  belongs_to :profile

  validates :job_title, presence: true
  validates :company_name, presence: true
  validates :company_url, :url => {:allow_blank => true}
  validates :from_date, presence: true
  validates :to_date, presence: true

  mount_uploader :image, ExperienceImageUploader

  # Include model in search
  include PgSearch
  multisearchable against: [:company_name, :description, :job_title]
  
  protected

  def smart_add_url_protocol
    unless self.company_url.empty?
      unless self.company_url.include?("http")
        unless self.company_url[/\^http:\/\//] || self.company_url[/\^https:\/\//]
          self.company_url = "http://#{self.company_url}"
        end
      end
    end
  end

end

app/controllers/experiences_controller.rb
class ExperiencesController < ApplicationController

  before_action :find_experience, only: [:edit, :update, :destroy]
  before_action :find_profile, only: [:edit, :update, :destroy]
  before_action :authenticate_user
  before_action :authorize_user, only: [:edit, :update, :destroy]

  def create
    @experience = Experience.new experience_params
    @experience.profile = current_user_profile
    # this stores an instance variable of profile just in case it needs to
    # be passed through when rendering the new page on error
    @profile = current_user_profile
    if @experience.save
      redirect_to edit_profile_path(current_user_profile, anchor: 'experience'), notice: "Work experience added!"
    else
      flash[:alert] = "Error adding work experience!"
      render :new
    end
  end

  def edit
  end

  def update
    if @experience.update experience_params
      redirect_to profile_path(current_user_profile, anchor: 'experience'), notice: "Work experience updated!"
    else
      flash[:alert] = "Error updating experience!"
      render new_profile_experience(@profile)
    end
  end

  def destroy
    @experience.destroy
    redirect_to profile_path(@profile, anchor: 'experience')
  end

  private

  def find_experience
    @experience = Experience.find params[:id]
  end

  def experience_params
    params.require(:experience).permit(:job_title, :description, :company_url, :image, :from_date, :to_date, :company_name)
  end

  def user_from_request
    Profile.find_by_id(params[:profile_id]).user
  end

  def authorize_user
    if !(can? :manage, @experience) || !((user_from_request == current_user) || (current_user.admin))
      redirect_to root_path, alert: "ACCESS DENIED"
    end
  end

end

app/helpers/experiences_helper.rb
module ExperiencesHelper
end

app/views/experiences/_display_experiences.html.erb
<div class="col-sm-12">
  <% @profile.experiences.order(created_at: :desc).each do |experience| %>
    <div class="row">
      <div class="col-sm-9">
        <% if experience.image %>
          <p class="logo-thumb">
            <%= image_tag experience.image.url(:logo_thumb) %>
          </p>
        <% end %>
        <h3><%= experience.job_title %> at <%= link_to "#{experience.company_name}", experience.company_url, target: "_blank" %></h3>
        <p>From: <%= parse_date(experience.from_date) %> to: <%= parse_date(experience.to_date) %></p>
        <p><%= experience.description %></p>
        <% if can? :manage, @profile %>
          <%= link_to "Edit", edit_profile_experience_path(@profile, experience), class: "btn btn-primary" %>
          <%= link_to "Delete", profile_experience_path(@profile, experience), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-primary" %>
        <% end %>
      </div>
      <div class="col-sm-3 text-right">
        <p class="profile-actions"></p>
        <p class="profile-actions"><%= link_to "Visit Company Site", experience.company_url, target: "_blank", class: "btn btn-default" %></p>
      </div>
    </div>
    <hr>
  <% end %>
</div>

app/views/experiences/_form.html.erb
<% if @experience %>
<ul>
  <% @experience.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
</ul>
<% end %>

<%= simple_form_for [@profile, @experience], html: {multiple: true} do |f| %>
  <%= f.input :job_title %>
  <%= f.input :company_name %>
  <%= f.input :company_url %>
  <%= f.input :description, as: :text %>
  <%= f.input :from_date, as: :date,
                            start_year: Date.today.year - 30 %>
  <%= f.input :to_date, as: :date,
                          start_year: Date.today.year - 30 %>
  <%= f.input :image, as: :file %>
  <div>
    <small>JPG, JPEG, GIF, PNG only.</small>
  </div><br />
  <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/experiences/edit.html.erb
<div class="col-sm-4 col-sm-offset-4">
<h1>Edit Experience</h1>

<%= render "form" %>
</div>

app/views/experiences/new.html.erb
<div class="col-sm-4 col-sm-offset-4">
<h1>Experience</h1>

<%= render "form" %>
</div>