config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get "/home" => "welcome#index"
  root "welcome#index"

  get '/search' => 'search#search'
  
  resources :sessions, only: [:new, :create, :destroy] do
    delete :destroy, on: :collection
  end

  resources :users do
    get :before_approval, on: :collection
  end
  resources :contacts, only: [:new, :create, :show]
  resources :categories

  resources :profiles do
    resources :projects
    resources :skills
    resources :educations
    resources :experiences
    resources :contacts, only: [:new, :create, :show]
  end

  resources :password_resets

  resources :contacts, only: [:new, :create]

  get "users/:id/edit_password" => "users#edit_password", as: :edit_password
  patch "users/:id/update_password" => "users#update_password"

  get "messages/data" => "messages#data"
  resources :messages

end

app/models/education.rb
class Education < ActiveRecord::Base
  before_validation :smart_add_url_protocol
  belongs_to :profile

  validates :school, presence: true
  validates :degree, presence: true
  validates :school_url, :url => {:allow_blank => true}
  validates :from_date, presence: true
  validates :to_date, presence: true

  mount_uploader :image, EducationImageUploader

  # Include model in search
  include PgSearch
  multisearchable against: [:degree, :description, :school]
  
  protected

  def smart_add_url_protocol
    unless self.school_url.empty?
      unless self.school_url.include?("http")
        unless self.school_url[/\^http:\/\//] || self.school_url[/\^https:\/\//]
          self.school_url = "http://#{self.school_url}"
        end
      end
    end
  end

end

app/controllers/educations_controller.rb
class EducationsController < ApplicationController

  before_action :find_education, only: [:edit, :update, :destroy]
  before_action :find_profile, only: [:edit, :update, :destroy]
  before_action :authenticate_user
  before_action :authorize_user, only: [:edit, :update, :destroy]

  def create
    @education = Education.new education_params
    @education.profile = current_user_profile
    # this stores an instance variable of profile just in case it needs to
    # be passed through when rendering the new page on error
    @profile = current_user_profile
    if @education.save
      redirect_to edit_profile_path(current_user_profile, anchor: 'education'), notice: "Education added!"
    else
      flash[:alert] = "Error adding education!"
      render :new
    end
  end

  def edit
  end

  def update
    if @education.update education_params
      redirect_to profile_path(current_user_profile, anchor: 'education'), notice: "Education updated!"
    else
      flash[:alert] = "Error updating education!"
      render new_profile_education(@profile)
    end

  end

  def destroy
    @education.destroy
    redirect_to profile_path(@profile, anchor: 'education')
  end

  private

  def find_education
    @education = Education.find params[:id]
  end

  def education_params
    params.require(:education).permit(:school, :image, :description, :school_url, :degree, :profile_id, :from_date, :to_date)
  end

  def user_from_request
    Profile.find_by_id(params[:profile_id]).user
  end

  def authorize_user
    if !(can? :manage, @education) || !((user_from_request == current_user) || (current_user.admin))
      redirect_to root_path, alert: "ACCESS DENIED"
    end
  end
end

app/helpers/educations_helper.rb
module EducationsHelper
end

app/views/educations/_display_education.html.erb
<div class="col-sm-12">
  <% @profile.educations.order(created_at: :desc).each do |education| %>
    <div class="row">
      <div class="col-sm-9">
        <% if education.image %>
          <div class="logo-thumb">
            <%= image_tag education.image.url(:logo_thumb) %>
          </div>
        <% end %>
        <h3><%= education.school %></h3>
        <p><strong><%= education.degree %></strong></p>
        <p>From: <%= parse_date(education.from_date) %> to: <%= parse_date(education.to_date) %></p>
        <p><%= education.description %></p>
        <% if can? :manage, @profile %>
          <%= link_to "Edit", edit_profile_education_path(@profile, education), class: "btn btn-primary" %>
          <%= link_to "Delete", profile_education_path(@profile, education), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-primary" %>
        <% end %>
      </div>
      <div class="col-sm-3 text-right">
        <p class="profile-actions"><%= link_to "Visit School", education.school_url, target: "_blank", class: "btn btn-default" %></p>
      </div>
    </div>
    <hr>
  <% end %>
</div>

app/views/educations/_form.html.erb
<ul>
  <% @education.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
</ul>

<%= simple_form_for [@profile, @education], html: {multiple: true} do |f| %>
  <%= f.input :school %>
  <%= f.input :degree %>
  <%= f.input :description, as: :text %>
  <%= f.input :from_date, as: :date,
                            start_year: Date.today.year - 30 %>
  <%= f.input :to_date, as: :date,
                          start_year: Date.today.year - 30 %>
  <%= f.input :school_url %>
  <%= f.input :image, as: :file %>
  <div>
    <small>JPG, JPEG, GIF, PNG only.</small>
  </div><br />
  <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/educations/edit.html.erb
<div class="col-sm-4 col-sm-offset-4">
  <h1>Edit Education</h1>

  <%= render "form" %>
</div>

app/views/educations/new.html.erb
<div class="col-sm-4 col-sm-offset-4">
<h1>Education</h1>

<%= render "form" %>
</div>